config/routes.rb
Rails.application.routes.draw do
  resources :committee_notices
  resources :travels
  resources :form_types
  resources :filers
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :address_types
  resources :addresses
  resources :treasurers
  resources :candidates
  resources :committee_types
  resources :report_types
  resources :election_types
  resources :office_helds
  resources :office_soughts
  resources :filer_types
  resources :loans
  resources :credits
  resources :investment_purchases
  resources :coh_payments
  resources :expenditures
  resources :contributions
  resources :campaign_finance_infos
  resources :contribution_types
  resources :entity_types
  resources :prefixes
  resources :expend_types
  resources :expend_categories
  resources :payment_methods
  resources :states
  resources :myreports

  authenticated :user do
    root :to => 'welcome#loginhome', as: :authenticated_root
  end
  root :to => 'welcome#home'

  get 'report', to: 'welcome#report'
  get 'registration', to: 'welcome#registration'
  get 'loginhome', to: 'welcome#loginhome'

  get '/search' => "campaign_finance_infos#search", as: 'search_query'
  get '/results' => "campaign_finance_infos#results"

end

app/models/address.rb
class Address < ActiveRecord::Base
belongs_to :state


end

app/models/address_type.rb
class AddressType < ActiveRecord::Base
has_many :addresses
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  has_many :campaign_finance_infos
end

app/models/coh_payment.rb
class CohPayment < ActiveRecord::Base
  belongs_to :campaign_finance_info
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  belongs_to :campaign_finance_info
  belongs_to :contribution_type

  validates_presence_of :amount
end

app/models/credit.rb
class Credit < ActiveRecord::Base
  belongs_to :campaign_finance_info
end

app/models/entity_type.rb
class EntityType < ActiveRecord::Base
end

app/models/expend_type.rb
class ExpendType < ActiveRecord::Base
end

app/models/expenditure.rb
class Expenditure < ActiveRecord::Base
  belongs_to :campaign_finance_info
end

app/models/filer.rb
class Filer < ActiveRecord::Base
  belongs_to :campaign_finance_info
  belongs_to :filer_type
  belongs_to :prefix
  belongs_to :office_sought
  belongs_to :office_held

  validates_presence_of :firstname
end

app/models/filer_type.rb
class FilerType < ActiveRecord::Base
end

app/models/form_type.rb
class FormType < ActiveRecord::Base
  has_many :travels
end

app/models/loan.rb
class Loan < ActiveRecord::Base
  belongs_to :campaign_finance_info
end

app/models/office_held.rb
class OfficeHeld < ActiveRecord::Base
end

app/models/prefix.rb
class Prefix < ActiveRecord::Base
end

app/models/report_type.rb
class ReportType < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/travel.rb
class Travel < ActiveRecord::Base
  belongs_to :campaign_finance_info
  belongs_to :form_type
end

app/models/treasurer.rb
class Treasurer < ActiveRecord::Base
  has_many :campaign_finance_infos
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :campaign_finance_infos
end

app/controllers/committee_types_controller.rb
class CommitteeTypesController < ApplicationController
  before_action :set_committee_type, only: [:show, :edit, :update, :destroy]

  # GET /committee_types
  # GET /committee_types.json
  def index
    @committee_types = CommitteeType.all
  end

  # GET /committee_types/1
  # GET /committee_types/1.json
  def show
  end

  # GET /committee_types/new
  def new
    @committee_type = CommitteeType.new
  end

  # GET /committee_types/1/edit
  def edit
  end

  # POST /committee_types
  # POST /committee_types.json
  def create
    @committee_type = CommitteeType.new(committee_type_params)

    respond_to do |format|
      if @committee_type.save
        format.html { redirect_to @committee_type, notice: 'Committee type was successfully created.' }
        format.json { render :show, status: :created, location: @committee_type }
      else
        format.html { render :new }
        format.json { render json: @committee_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /committee_types/1
  # PATCH/PUT /committee_types/1.json
  def update
    respond_to do |format|
      if @committee_type.update(committee_type_params)
        format.html { redirect_to @committee_type, notice: 'Committee type was successfully updated.' }
        format.json { render :show, status: :ok, location: @committee_type }
      else
        format.html { render :edit }
        format.json { render json: @committee_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /committee_types/1
  # DELETE /committee_types/1.json
  def destroy
    @committee_type.destroy
    respond_to do |format|
      format.html { redirect_to committee_types_url, notice: 'Committee type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_committee_type
      @committee_type = CommitteeType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def committee_type_params
      params.require(:committee_type).permit(:comtype)
    end
end

app/helpers/committee_types_helper.rb
module CommitteeTypesHelper
end

app/views/committee_types/_form.html.erb
<%= form_for(@committee_type) do |f| %>
  <% if @committee_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@committee_type.errors.count, "error") %> prohibited this committee_type from being saved:</h2>

      <ul>
      <% @committee_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comtype %><br>
    <%= f.text_field :comtype %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/committee_types/edit.html.erb
<h1>Editing Committee Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @committee_type %> |
<%= link_to 'Back', committee_types_path %>

app/views/committee_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Committee Types</h1>

<table>
  <thead>
    <tr>
      <th>Comtype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @committee_types.each do |committee_type| %>
      <tr>
        <td><%= committee_type.comtype %></td>
        <td><%= link_to 'Show', committee_type %></td>
        <td><%= link_to 'Edit', edit_committee_type_path(committee_type) %></td>
        <td><%= link_to 'Destroy', committee_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Committee type', new_committee_type_path %>

app/views/committee_types/new.html.erb
<h1>New Committee Type</h1>

<%= render 'form' %>

<%= link_to 'Back', committee_types_path %>

app/views/committee_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comtype:</strong>
  <%= @committee_type.comtype %>
</p>

<%= link_to 'Edit', edit_committee_type_path(@committee_type) %> |
<%= link_to 'Back', committee_types_path %>