config/routes.rb
Rails.application.routes.draw do
  resources :committee_notices
  resources :travels
  resources :form_types
  resources :filers
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :address_types
  resources :addresses
  resources :treasurers
  resources :candidates
  resources :committee_types
  resources :report_types
  resources :election_types
  resources :office_helds
  resources :office_soughts
  resources :filer_types
  resources :loans
  resources :credits
  resources :investment_purchases
  resources :coh_payments
  resources :expenditures
  resources :contributions
  resources :campaign_finance_infos
  resources :contribution_types
  resources :entity_types
  resources :prefixes
  resources :expend_types
  resources :expend_categories
  resources :payment_methods
  resources :states
  resources :myreports

  authenticated :user do
    root :to => 'welcome#loginhome', as: :authenticated_root
  end
  root :to => 'welcome#home'

  get 'report', to: 'welcome#report'
  get 'registration', to: 'welcome#registration'
  get 'loginhome', to: 'welcome#loginhome'

  get '/search' => "campaign_finance_infos#search", as: 'search_query'
  get '/results' => "campaign_finance_infos#results"

end

app/models/address.rb
class Address < ActiveRecord::Base
belongs_to :state


end

app/models/address_type.rb
class AddressType < ActiveRecord::Base
has_many :addresses
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  has_many :campaign_finance_infos
end

app/models/coh_payment.rb
class CohPayment < ActiveRecord::Base
  belongs_to :campaign_finance_info
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  belongs_to :campaign_finance_info
  belongs_to :contribution_type

  validates_presence_of :amount
end

app/models/credit.rb
class Credit < ActiveRecord::Base
  belongs_to :campaign_finance_info
end

app/models/entity_type.rb
class EntityType < ActiveRecord::Base
end

app/models/expend_type.rb
class ExpendType < ActiveRecord::Base
end

app/models/expenditure.rb
class Expenditure < ActiveRecord::Base
  belongs_to :campaign_finance_info
end

app/models/filer.rb
class Filer < ActiveRecord::Base
  belongs_to :campaign_finance_info
  belongs_to :filer_type
  belongs_to :prefix
  belongs_to :office_sought
  belongs_to :office_held

  validates_presence_of :firstname
end

app/models/filer_type.rb
class FilerType < ActiveRecord::Base
end

app/models/form_type.rb
class FormType < ActiveRecord::Base
  has_many :travels
end

app/models/loan.rb
class Loan < ActiveRecord::Base
  belongs_to :campaign_finance_info
end

app/models/office_held.rb
class OfficeHeld < ActiveRecord::Base
end

app/models/payment_method.rb
class PaymentMethod < ActiveRecord::Base
end

app/models/prefix.rb
class Prefix < ActiveRecord::Base
end

app/models/report_type.rb
class ReportType < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/travel.rb
class Travel < ActiveRecord::Base
  belongs_to :campaign_finance_info
  belongs_to :form_type
end

app/models/treasurer.rb
class Treasurer < ActiveRecord::Base
  has_many :campaign_finance_infos
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :campaign_finance_infos
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  before_action :set_payment_method, only: [:show, :edit, :update, :destroy]

  # GET /payment_methods
  # GET /payment_methods.json
  def index
    @payment_methods = PaymentMethod.all
  end

  # GET /payment_methods/1
  # GET /payment_methods/1.json
  def show
  end

  # GET /payment_methods/new
  def new
    @payment_method = PaymentMethod.new
  end

  # GET /payment_methods/1/edit
  def edit
  end

  # POST /payment_methods
  # POST /payment_methods.json
  def create
    @payment_method = PaymentMethod.new(payment_method_params)

    respond_to do |format|
      if @payment_method.save
        format.html { redirect_to @payment_method, notice: 'Payment method was successfully created.' }
        format.json { render :show, status: :created, location: @payment_method }
      else
        format.html { render :new }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_methods/1
  # PATCH/PUT /payment_methods/1.json
  def update
    respond_to do |format|
      if @payment_method.update(payment_method_params)
        format.html { redirect_to @payment_method, notice: 'Payment method was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_method }
      else
        format.html { render :edit }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_methods/1
  # DELETE /payment_methods/1.json
  def destroy
    @payment_method.destroy
    respond_to do |format|
      format.html { redirect_to payment_methods_url, notice: 'Payment method was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_method
      @payment_method = PaymentMethod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_method_params
      params.require(:payment_method).permit(:paymentmethod)
    end
end

app/helpers/payment_methods_helper.rb
module PaymentMethodsHelper
end

app/views/payment_methods/_form.html.erb
<%= form_for(@payment_method) do |f| %>
  <% if @payment_method.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment_method.errors.count, "error") %> prohibited this payment_method from being saved:</h2>

      <ul>
      <% @payment_method.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :paymentmethod %><br>
    <%= f.text_field :paymentmethod %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payment_methods/edit.html.erb
<h1>Editing Payment Method</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_method %> |
<%= link_to 'Back', payment_methods_path %>

app/views/payment_methods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Payment Methods</h1>

<table>
  <thead>
    <tr>
      <th>Paymentmethod</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_methods.each do |payment_method| %>
      <tr>
        <td><%= payment_method.paymentmethod %></td>
        <td><%= link_to 'Show', payment_method %></td>
        <td><%= link_to 'Edit', edit_payment_method_path(payment_method) %></td>
        <td><%= link_to 'Destroy', payment_method, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment method', new_payment_method_path %>

app/views/payment_methods/new.html.erb
<h1>New Payment Method</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_methods_path %>

app/views/payment_methods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Paymentmethod:</strong>
  <%= @payment_method.paymentmethod %>
</p>

<%= link_to 'Edit', edit_payment_method_path(@payment_method) %> |
<%= link_to 'Back', payment_methods_path %>