config/routes.rb
Rails.application.routes.draw do
  resources :committee_notices
  resources :travels
  resources :form_types
  resources :filers
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :address_types
  resources :addresses
  resources :treasurers
  resources :candidates
  resources :committee_types
  resources :report_types
  resources :election_types
  resources :office_helds
  resources :office_soughts
  resources :filer_types
  resources :loans
  resources :credits
  resources :investment_purchases
  resources :coh_payments
  resources :expenditures
  resources :contributions
  resources :campaign_finance_infos
  resources :contribution_types
  resources :entity_types
  resources :prefixes
  resources :expend_types
  resources :expend_categories
  resources :payment_methods
  resources :states
  resources :myreports

  authenticated :user do
    root :to => 'welcome#loginhome', as: :authenticated_root
  end
  root :to => 'welcome#home'

  get 'report', to: 'welcome#report'
  get 'registration', to: 'welcome#registration'
  get 'loginhome', to: 'welcome#loginhome'

  get '/search' => "campaign_finance_infos#search", as: 'search_query'
  get '/results' => "campaign_finance_infos#results"

end

app/models/address.rb
class Address < ActiveRecord::Base
belongs_to :state


end

app/models/address_type.rb
class AddressType < ActiveRecord::Base
has_many :addresses
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  has_many :campaign_finance_infos
end

app/models/coh_payment.rb
class CohPayment < ActiveRecord::Base
  belongs_to :campaign_finance_info
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  belongs_to :campaign_finance_info
  belongs_to :contribution_type

  validates_presence_of :amount
end

app/models/credit.rb
class Credit < ActiveRecord::Base
  belongs_to :campaign_finance_info
end

app/models/entity_type.rb
class EntityType < ActiveRecord::Base
end

app/models/expend_type.rb
class ExpendType < ActiveRecord::Base
end

app/models/expenditure.rb
class Expenditure < ActiveRecord::Base
  belongs_to :campaign_finance_info
end

app/models/filer.rb
class Filer < ActiveRecord::Base
  belongs_to :campaign_finance_info
  belongs_to :filer_type
  belongs_to :prefix
  belongs_to :office_sought
  belongs_to :office_held

  validates_presence_of :firstname
end

app/models/filer_type.rb
class FilerType < ActiveRecord::Base
end

app/models/form_type.rb
class FormType < ActiveRecord::Base
  has_many :travels
end

app/models/loan.rb
class Loan < ActiveRecord::Base
  belongs_to :campaign_finance_info
end

app/models/office_held.rb
class OfficeHeld < ActiveRecord::Base
end

app/models/prefix.rb
class Prefix < ActiveRecord::Base
end

app/models/report_type.rb
class ReportType < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/travel.rb
class Travel < ActiveRecord::Base
  belongs_to :campaign_finance_info
  belongs_to :form_type
end

app/models/treasurer.rb
class Treasurer < ActiveRecord::Base
  has_many :campaign_finance_infos
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :campaign_finance_infos
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end

  def report

  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/home.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Heroic Features - Start Bootstrap Template</title>

  <!-- Bootstrap Core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="css/heroic-features.css" rel="stylesheet">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body>

<!-- Page Content -->
<div class="container">

  <!-- Jumbotron Header -->
  <header class="jumbotron hero-spacer">
    <h1 style="color:navy;">The City of Houston</h1>
    <p style="color:darkslategray;">Campaign Finance Application Module</p>
  </header>

  <hr>

  <!-- Title -->
  <div class="row">
    <div class="col-lg-12">
      <h3>Module Features</h3>
    </div>
  </div>
  <!-- /.row -->


  <!-- Page Features -->
  <div class="row text-center">

    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <img src="assets/search.png" alt="">
        <div class="caption">
          <h3>Search</h3>
          <p>Search for filed Campaign Finance Reports.</p>
          <p>
            <a href="http://localhost:3000/search" class="btn btn-default">Search</a>
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <img src="assets/report.png" alt="">
        <div class="caption">
          <h3>File Report</h3>
          <p>File a Report.</p>
          <p>
            <a href="http://localhost:3000/users/sign_in" class="btn btn-default">File a Report</a>
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <img src="assets/manual.png" alt="">
        <div class="caption">
          <h3>Instructions</h3>
          <p>Instructions to file a Campaign Finance Report.</p>
          <p>
            <a href="#" class="btn btn-default">Instructions</a>
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <img src="assets/password.png" alt="">
        <div class="caption">
          <h3>Request Password</h3>
          <p>Candidate filers are required to request credentials.</p>
          <p>
           <a href="http://www.houstontx.gov/campaignfinance/passwordForm053107.pdf" class="btn btn-default">Request</a>
          </p>
        </div>
      </div>
    </div>

  </div>
  <!-- /.row -->

  <hr>

  <!-- Footer -->
  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; Incognito Tech Solutions 2016</p>
      </div>
    </div>
  </footer>

</div>
<!-- /.container -->

<!-- jQuery -->
<script src="js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

</body>

</html>

app/views/welcome/loginhome.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Blog Home Template for Bootstrap 3</title>

  <!-- Bootstrap core CSS -->
  <link href="css/bootstrap.css" rel="stylesheet">

  <!-- Add custom CSS here -->
  <link href="css/blog-home.css" rel="stylesheet">

</head>

<body>

<div class="container">

  <div class="row">
    <div class="col-lg-8">

      <!-- blog entry -->
      <h1 style="color:navy;">Welcome!</a>
      </h1>
      <p class="lead">City of Houston Campaign Finance Application Module</a>
      </p>
      <hr>
      <hr>
      <p>Welcome to the City of Houston Campaign Finance Application. The links on the right will help you navigate through the module.
        Please read the instructions provided to help you start the Campaign Finanace Report Process. </p>


      <hr>
      <div class="well">
        <h4 style="color:red;">DISCLAIMER</h4>
        <p>Electronic data entered into this system will be subject to Texas Public Information Act requests. Disclosure of the information will be required unless exempted under a specific provision of the Act.</br>
          <br>The law requires that data entered into this system be readily available to the public within two (2) business days.</br>
          Enter only data required by Title 15 of the Texas Election Code, and Chapter 18 of the Code of Ordinances, Houston TX.</p>
      </div>

    </div>

    <div class="col-lg-4">

      <!-- /well -->
      <div class="well">
        <h4 style="color:darkgreen;">Campaign Finance Navigation</h4>
        <div class="row">
          <div class="col-lg-10">
            <ul class="list-center">
              <li><%= link_to "Home", loginhome_path %></a>
              </li>
              <li><%= link_to "New Report", new_campaign_finance_info_path %></a>
              </li>
              <li><%= link_to "My Reports", campaign_finance_infos_path %></a>
              </li>
              <li><%= link_to "Instructions", campaign_finance_infos_path %></a>
              </li>
            </ul>
          </div>
        </div>
      </div>


      <div class="well">
        <h4 style="color:darkgreen;">Registration</h4>
        <div class="row">
          <div class="col-lg-10">
            <ul class="list-center">
              <li><%= link_to "Register Candidate", new_candidate_path %></a>
              </li>
              <li><%= link_to "Register Treasurer", new_treasurer_path %></a>
              </li>
            </ul>
          </div>
        </div>
      </div>


      <div class="well">
        <h4 style="color:darkgreen;">City of Houston Links</h4>
        <div class="row">
          <div class="col-lg-10">
            <ul class="list-center">
              <li><a href="http://www.houstontx.gov/">City of Houston</a>
              </li>
              <li><a href="http://www.houstontx.gov/council/">City Council</a>
              </li>
              <li><a href="http://www.houstontx.gov/redirect/harriscountyclerk.html">County Clerk</a>
              </li>
              <li><a href="http://www.houstontx.gov/citysec/">City Secretary</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <!-- /well -->
      <!-- /well -->
    </div>
  </div>

  <hr>

  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; Incognito Tech Solutions 2016</p>
      </div>
    </div>
  </footer>

</div>
<!-- /.container -->

<!-- JavaScript -->
<script src="js/jquery-1.10.2.js"></script>
<script src="js/bootstrap.js"></script>

</body>

</html>

app/views/welcome/report.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Heroic Features - Start Bootstrap Template</title>

  <!-- Bootstrap Core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="css/heroic-features.css" rel="stylesheet">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body>

<!-- Page Content -->
<div class="container">

  <!-- Jumbotron Header -->
  <header class="jumbotron hero-spacer">
    <h1>The City of Houston</h1>
    <p>Camapaign Finance Information System</p>
  </header>

  <hr>

  <!-- Title -->
  <div class="row">
    <div class="col-lg-12">
      <h3>Latest Features</h3>
    </div>
  </div>
  <!-- /.row -->

  <!-- Page Features -->
  <div class="row text-center">

    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <img src="http://placehold.it/800x500" alt="">
        <div class="caption">
          <h3>Feature Label</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
          <p>
            <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <img src="http://placehold.it/800x500" alt="">
        <div class="caption">
          <h3>Feature Label</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
          <p>
            <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <img src="http://placehold.it/800x500" alt="">
        <div class="caption">
          <h3>Feature Label</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
          <p>
            <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <img src="http://placehold.it/800x500" alt="">
        <div class="caption">
          <h3>Feature Label</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
          <p>
            <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
          </p>
        </div>
      </div>
    </div>

  </div>
  <!-- /.row -->

  <hr>

  <!-- Footer -->
  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; Incognito Tech Solutions 2016</p>
      </div>
    </div>
  </footer>

</div>
<!-- /.container -->

<!-- jQuery -->
<script src="js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

</body>

</html>