config/routes.rb
Rails.application.routes.draw do
  resources :committee_notices
  resources :travels
  resources :form_types
  resources :filers
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :address_types
  resources :addresses
  resources :treasurers
  resources :candidates
  resources :committee_types
  resources :report_types
  resources :election_types
  resources :office_helds
  resources :office_soughts
  resources :filer_types
  resources :loans
  resources :credits
  resources :investment_purchases
  resources :coh_payments
  resources :expenditures
  resources :contributions
  resources :campaign_finance_infos
  resources :contribution_types
  resources :entity_types
  resources :prefixes
  resources :expend_types
  resources :expend_categories
  resources :payment_methods
  resources :states
  resources :myreports

  authenticated :user do
    root :to => 'welcome#loginhome', as: :authenticated_root
  end
  root :to => 'welcome#home'

  get 'report', to: 'welcome#report'
  get 'registration', to: 'welcome#registration'
  get 'loginhome', to: 'welcome#loginhome'

  get '/search' => "campaign_finance_infos#search", as: 'search_query'
  get '/results' => "campaign_finance_infos#results"

end

app/models/address.rb
class Address < ActiveRecord::Base
belongs_to :state


end

app/models/address_type.rb
class AddressType < ActiveRecord::Base
has_many :addresses
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  has_many :campaign_finance_infos
end

app/models/coh_payment.rb
class CohPayment < ActiveRecord::Base
  belongs_to :campaign_finance_info
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  belongs_to :campaign_finance_info
  belongs_to :contribution_type

  validates_presence_of :amount
end

app/models/contribution_type.rb
class ContributionType < ActiveRecord::Base
  has_many :contributions
end

app/models/credit.rb
class Credit < ActiveRecord::Base
  belongs_to :campaign_finance_info
end

app/models/entity_type.rb
class EntityType < ActiveRecord::Base
end

app/models/expend_type.rb
class ExpendType < ActiveRecord::Base
end

app/models/expenditure.rb
class Expenditure < ActiveRecord::Base
  belongs_to :campaign_finance_info
end

app/models/filer.rb
class Filer < ActiveRecord::Base
  belongs_to :campaign_finance_info
  belongs_to :filer_type
  belongs_to :prefix
  belongs_to :office_sought
  belongs_to :office_held

  validates_presence_of :firstname
end

app/models/filer_type.rb
class FilerType < ActiveRecord::Base
end

app/models/form_type.rb
class FormType < ActiveRecord::Base
  has_many :travels
end

app/models/loan.rb
class Loan < ActiveRecord::Base
  belongs_to :campaign_finance_info
end

app/models/office_held.rb
class OfficeHeld < ActiveRecord::Base
end

app/models/prefix.rb
class Prefix < ActiveRecord::Base
end

app/models/report_type.rb
class ReportType < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/travel.rb
class Travel < ActiveRecord::Base
  belongs_to :campaign_finance_info
  belongs_to :form_type
end

app/models/treasurer.rb
class Treasurer < ActiveRecord::Base
  has_many :campaign_finance_infos
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :campaign_finance_infos
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :set_contribution, only: [:show, :edit, :update, :destroy]

  # GET /contributions
  # GET /contributions.json
  def index
    @contributions = Contribution.all
  end

  # GET /contributions/1
  # GET /contributions/1.json
  def show
  end

  # GET /contributions/new
  def new
    @contribution = Contribution.new
  end

  # GET /contributions/1/edit
  def edit
  end

  # POST /contributions
  # POST /contributions.json
  def create
    @contribution = Contribution.new(contribution_params)

    respond_to do |format|
      if @contribution.save
        format.html { redirect_to @contribution, notice: 'Contribution was successfully created.' }
        format.json { render :show, status: :created, location: @contribution }
      else
        format.html { render :new }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contributions/1
  # PATCH/PUT /contributions/1.json
  def update
    respond_to do |format|
      if @contribution.update(contribution_params)
        format.html { redirect_to @contribution, notice: 'Contribution was successfully updated.' }
        format.json { render :show, status: :ok, location: @contribution }
      else
        format.html { render :edit }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contributions/1
  # DELETE /contributions/1.json
  def destroy
    @contribution.destroy
    respond_to do |format|
      format.html { redirect_to contributions_url, notice: 'Contribution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contribution
      @contribution = Contribution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contribution_params
      params.require(:contribution).permit(:campaign_finance_info_id, :contribution_type_id, :prefix_id, :entity_type_id, :contributorname, :address, :city, :state_id, :zip, :amount, :date, :description, :isoutofstatepac, :pacid, :istraveloutsidetx)
    end
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/contributions/_form.html.erb
<%= form_for @contribution,:validate => true do |f|%>
  <% if @contribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contribution.errors.count, "error") %> prohibited this contribution from being saved:</h2>

      <ul>
      <% @contribution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :campaign_finance_info_id %><br>
    <%= f.number_field :campaign_finance_info_id %>
  </div>
  <div class="field">
    <%= f.label :contribution_type_id %><br>
    <%= f.number_field :contribution_type_id %>
  </div>
  <div class="field">
    <%= f.label :prefix_id %><br>
    <%= f.number_field :prefix_id %>
  </div>
  <div class="field">
    <%= f.label :entity_type_id %><br>
    <%= f.number_field :entity_type_id %>
  </div>
  <div class="field">
    <%= f.label :contributorname %><br>
    <%= f.text_field :contributorname %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state_id %><br>
    <%= f.number_field :state_id %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

    <% case $outofstatepac %>

    <% when '1' %>

        <div class="field">
          <%= f.label :isoutofstatepac %><br>
          <%= f.check_box :isoutofstatepac, :checked => true  %>
        </div>

    <% when '0' %>

        <div class="field">
          <%= f.label :isoutofstatepac %><br>
          <%= f.check_box :isoutofstatepac, :checked => false  %>
        </div>

    <% else %>

        <div class="field">
          <%= f.label :isoutofstatepac %><br>
          <%= f.check_box :isoutofstatepac, :checked => false %>
        </div>

    <% end %>

  <div class="field">
    <%= f.label :pacid %><br>
    <%= f.text_field :pacid %>
  </div>

    <% case $traveloutsidetx %>

    <% when '1' %>

        <div class="field">
          <%= f.label :istraveloutsidetx %><br>
          <%= f.check_box :istraveloutsidetx, :checked => true %>
        </div>

    <% when '0' %>

        <div class="field">
          <%= f.label :istraveloutsidetx %><br>
          <%= f.check_box :istraveloutsidetx, :checked => false %>
        </div>

    <% when '0' %>

        <div class="field">
          <%= f.label :istraveloutsidetx %><br>
          <%= f.check_box :istraveloutsidetx, :checked => false %>
        </div>

    <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contributions/edit.html.erb
<h1>Editing Contribution</h1>

<%= render 'form' %>

<%= link_to 'Show', @contribution %> |
<%= link_to 'Back', contributions_path %>

app/views/contributions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contributions</h1>

<table>
  <thead>
    <tr>
      <th>Campaign finance info</th>
      <th>Contribution type</th>
      <th>Prefix</th>
      <th>Entity type</th>
      <th>Contributorname</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Amount</th>
      <th>Date</th>
      <th>Description</th>
      <th>Isoutofstatepac</th>
      <th>Pacid</th>
      <th>Istraveloutsidetx</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contributions.each do |contribution| %>
      <tr>
        <td><%= contribution.campaign_finance_info_id %></td>
        <td><%= contribution.contribution_type_id %></td>
        <td><%= contribution.prefix_id %></td>
        <td><%= contribution.entity_type_id %></td>
        <td><%= contribution.contributorname %></td>
        <td><%= contribution.address %></td>
        <td><%= contribution.city %></td>
        <td><%= contribution.state_id %></td>
        <td><%= contribution.zip %></td>
        <td><%= contribution.amount %></td>
        <td><%= contribution.date %></td>
        <td><%= contribution.description %></td>
        <td><%= contribution.isoutofstatepac %></td>
        <td><%= contribution.pacid %></td>
        <td><%= contribution.istraveloutsidetx %></td>
        <td><%= link_to 'Show', contribution %></td>
        <td><%= link_to 'Edit', edit_contribution_path(contribution) %></td>
        <td><%= link_to 'Destroy', contribution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contribution', new_contribution_path %>

app/views/contributions/new.html.erb
<h1>New Contribution</h1>

<%= render 'form' %>

<%= link_to 'Back', contributions_path %>

app/views/contributions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Campaign finance info:</strong>
  <%= @contribution.campaign_finance_info_id %>
</p>

<p>
  <strong>Contribution type:</strong>
  <%= @contribution.contribution_type_id %>
</p>

<p>
  <strong>Prefix:</strong>
  <%= @contribution.prefix_id %>
</p>

<p>
  <strong>Entity type:</strong>
  <%= @contribution.entity_type_id %>
</p>

<p>
  <strong>Contributorname:</strong>
  <%= @contribution.contributorname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contribution.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @contribution.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @contribution.state_id %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @contribution.zip %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @contribution.amount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @contribution.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @contribution.description %>
</p>

<p>
  <strong>Isoutofstatepac:</strong>
  <%= @contribution.isoutofstatepac %>
</p>

<p>
  <strong>Pacid:</strong>
  <%= @contribution.pacid %>
</p>

<p>
  <strong>Istraveloutsidetx:</strong>
  <%= @contribution.istraveloutsidetx %>
</p>

<%= link_to 'Edit', edit_contribution_path(@contribution) %> |
<%= link_to 'Back', contributions_path %>